name: Learning Progress Automation

on:
  schedule:
    - cron: '0 15 * * *'   # 8:30 PM IST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update learning log
        run: |
          DAY=$(date +%j)
          echo "- Day $DAY: Practiced DSA / C++ / revision" >> learning.md

      - name: Commit changes
        run: |
         git config user.name "Vivekk078"
          git config user.email "pantvivek098@gmail.com"

          git add learning.md
          git commit -m "Daily learning update" || echo "No changes"
          git push
